Repository pantos-io/servicenode, pull requests merged in 2024-10, with the labels that each got.

#109 [PAN-2197] Protocol v0.1.0 support
  .mypy.ini
  pantos/servicenode/blockchains/base.py
  pantos/servicenode/blockchains/ethereum.py
  pantos/servicenode/blockchains/solana.py
  pantos/servicenode/business/bids.py
  pantos/servicenode/business/node.py
  pantos/servicenode/configuration.py
  pantos/servicenode/database/access.py
  pantos/servicenode/plugins/bids.py
  pantos/servicenode/protocol.py
  pantos/servicenode/restapi.py
  poetry.lock
  pyproject.toml
  service-node-config.docker.env
  service-node-config.env
  service-node-config.local.env
  service-node-config.yml
  tests/blockchains/test_base.py
  tests/blockchains/test_ethereum.py
  tests/business/test_bids.py
  tests/business/test_node.py
  tests/business/test_transfers.py
  tests/conftest.py
  tests/database/conftest.py
  tests/database/sqlite/access/test_read_bids.py
  tests/database/sqlite/access/test_read_transfer_by_task_id.py
  tests/restapi/test_bids.py
  tests/test_protocol.py
Labels: enhancement

#120 [PAN-2276] Insert enum values into database only if run by web server
  pantos/servicenode/database/__init__.py
  tests/database/test_initialize_package.py
Labels: bug

#124 fix: remove validator fee from same-blockchain bids
  docker-compose.yml
  pantos/servicenode/business/plugins.py
Labels: bug

#126 [PAN-2261] [PAN-2262] Support for Polygon and Sonic blockchains
  .gitignore
  bids.yml
  pantos/servicenode/blockchains/sonic.py
  poetry.lock
  pyproject.toml
  service-node-config.docker.env
  service-node-config.env
  service-node-config.local.env
  service-node-config.yml
  tests/blockchains/test_base.py
  tests/blockchains/test_factory.py
  tests/blockchains/test_fantom.py
  tests/blockchains/test_sonic.py
  tests/business/test_node.py
Labels: enhancement

#133 [PAN-2275] Upgrade psycopg
  configurator/DEBIAN/postinst
  docker-compose.yml
  poetry.lock
  pyproject.toml
  service-node-config.env
  service-node-config.local.env
  tests/database/conftest.py
Labels: dependencies

#136 docs: improve start web server logging
  linux/scripts/start-web.py
Labels: documentation
