Repository pantos-io/servicenode, pull requests merged in 2024-07, with the labels that each got.

#46 [PAN-2071] remove all cache entries from branch
  .github/workflows/clean.yaml
  .github/workflows/docker-vulnerabilities.yaml
Labels: enhancement

#48 [PAN-2074] Do not disclose starting server command
  linux/scripts/start-web.py
Labels: security

#47 [PAN-2069] add blockchain rpcs check
  pantos/servicenode/application.py
  pantos/servicenode/configuration.py
  pantos/servicenode/restapi.py
  poetry.lock
  pyproject.toml
  tests/test_application.py
  tests/test_configuration.py
Labels: enhancement

#53 [PAN-2080] bids config object creation
  pantos/servicenode/plugins/bids.py
Labels: enhancement

#56 fix disclosing data command
  linux/scripts/start-web.py
Labels: bug

#54 [PAN-1998] Upgrade to hexbytes 1.x
  pantos/servicenode/blockchains/ethereum.py
  poetry.lock
  pyproject.toml
  tests/blockchains/test_ethereum.py
Labels: dependencies
